// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";
import { sleep } from "k6";

export let options = { 
  stages: [
    { duration: '1m', target: 50 },
    { duration: '1m', target: 120 },
    { duration: '2m', target: 70 },
    { duration: '1m', target: 0 },
  ],
};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "localhost:3000/tasks/1",
    id: "e7688ea6-cafb-453f-afab-be312238d852",
    method: "GET",
    address: "http://localhost:3000/tasks/{{$randomInt}}"
  });

  postman[Request]({
    name: "localhost:3000/offers?merchantId=10",
    id: "f19d3ee9-7943-43e0-9e9c-5dde43f7fea8",
    method: "GET",
    address:
      "http://localhost:3000/offers?offerId={{$randomInt}}&merchantId={{$randomInt}}"
  });
  sleep(0.075);
}
