// Auto-generated by the Load Impact converter

import { sleep } from "k6";
import "./libs/shim/core.js";

export let options = { 
  stages: [
    { duration: '1m', target: 100 },
    { duration: '1m', target: 250 },
    { duration: '1m', target: 200 },
    { duration: '1m', target: 50 },
  ],
};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "localhost:3000/merchants/{id}",
    id: "f2a6abfd-a6ed-45fc-8f99-bd3fb1163f51",
    method: "PUT",
    address: "http://localhost:3000/merchants/{{$randomInt}}",
    data: '{\r\n    "link":"http://localhost:3001/offers_short.xlsx"\r\n}'
  });
  sleep(1);
}
