// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/merchants/{id}": {
            "put": {
                "description": "Проверяет полученную в теле ссылку\nВозвращает Content-Location созданной задачи по обработке\nЗапускает горутину для обработки файла",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Инициирует обработку файла",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Merchant ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Link to .xlsx file",
                        "name": "merchantPutRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Link"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/CommonResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/CommonResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/CommonResponse"
                        }
                    }
                }
            }
        },
        "/offers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Возвращает массив Продавцов с Товарами, отфильтрованными по опциональным параметрам",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID товара",
                        "name": "offerId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ID продавца",
                        "name": "merhcantId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Подстрока названия",
                        "name": "sub",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Merchant"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/CommonResponse"
                        }
                    }
                }
            }
        },
        "/tasks/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Возвращает статистику по запущенному заданию",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Task"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/CommonResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "CommonResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "Link": {
            "type": "object",
            "required": [
                "link"
            ],
            "properties": {
                "link": {
                    "type": "string",
                    "example": "http://file-server.com/offers_table.xlsx"
                }
            }
        },
        "Merchant": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "offers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Offer"
                    }
                }
            }
        },
        "Offer": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "Task": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "integer"
                },
                "deleted": {
                    "type": "integer"
                },
                "isCompleted": {
                    "type": "boolean"
                },
                "missed": {
                    "type": "integer"
                },
                "timeSpent": {
                    "description": "should be time.Duration, made as string for fancy output",
                    "type": "string"
                },
                "updated": {
                    "type": "integer"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "localhost",
	BasePath:    ":3000/",
	Schemes:     []string{},
	Title:       "MerchantX Trainee API",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
